version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: keycloak_postgres
    restart: always
    environment:
      POSTGRES_USER: dsv
      POSTGRES_PASSWORD: a1s2d3f4g5
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/volumes/postgresql/data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    command: "start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false"
    restart: always
    environment:
      KC_HOSTNAME: "localhost"
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_ENABLED: "false"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KEYCLOAK_ADMIN: dsv
      KEYCLOAK_ADMIN_PASSWORD: a1s2d3f4g5
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_DB_USERNAME: dsv
      KC_DB_PASSWORD: a1s2d3f4g5
      KC_LOG_LEVEL: "info"
      KC_PROXY: "edge"
      KC_PROXY_HEADERS: "xforwarded"
      KC_HOSTNAME_DEBUG: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./themes:/opt/keycloak/themes
    depends_on:
      - postgres

# volumes:
#   postgres_data:
#     device: ":/path/to/share"