name: CD

on:
  workflow_dispatch:
  
env:
  APP_VERSION: ${{github.sha}}
  
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: APP_VERSION
      run: echo "APP_VERSION=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      
    - name: Deploy Keycloak
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        KEYCLOAK_ADMIN: ${{ secrets.KEYCLOAK_ADMIN }}
        KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      shell: bash
      run: |
        sshpass -p $SSH_PASSWORD ssh -o ExitOnForwardFailure=yes -o StrictHostKeyChecking=no -fN -L 4646:127.0.0.1:4646 root@207.180.240.28 sleep 240 & \
        sleep 10 && \
        curl https://releases.hashicorp.com/nomad/1.4.3/nomad_1.4.3_linux_amd64.zip -o nomad.zip && \
        unzip nomad.zip && \
        chmod +x nomad && \
        ./nomad run --var="admin_password=${KEYCLOAK_ADMIN_PASSWORD}" --var="admin_user=${KEYCLOAK_ADMIN}" --var="db_password=${POSTGRES_PASSWORD}" --var="db_user=${POSTGRES_USER}" --var="cpu=200" --var="memory=1000" deploy.hcl
                    